### ISSUE TITLE
大佬好，关于触摸板问题

### ISSUE THREAD

**Issue by flydzy** [blankqwq/asus-fl5900u-hackintosh-oc#1]
我尝试过直接替换您的驱动，也就是将您OC文件替换我自己的，然后就不能开机了，尝试使用PS2替换我自己的PS2，也是不能开机。而我自己本身的触摸板完全无法识别和驱动，型号跟您也是一样，请问有什么办法嘛

**Comment by blankqwq** [comment]
抱歉，我没有打触摸板打驱动。不能开机的话，有没有错误代码

**Comment by flydzy** [comment]
用的OC 0.7.6，直接就是卡苹果的图标了。系统是big sur 11.6，几乎所有的驱动都不能驱动触摸板，谢谢大佬的回复

**Comment by blankqwq** [comment]
bios是否关闭了安全启动,cms,还有一些要求关闭的选项，我的config没有开启oc的cfglock选项，而是通过efi(Cfglock)进行关闭的(value:0)。我这里其他驱动均已正常，开机也不卡代码，目前已升级至12.1

**Comment by blankqwq** [comment]
你可以删除我的非必要驱动(网卡驱动,蓝牙驱动),刚刚用efi进入了备用的11.6系统，貌似没有问题

**Comment by flydzy** [comment]
您好，我装了个monterey 12.01 ，您方便分享一下您目前在用的EFI文件吗，我对驱动这一块也不是特别熟，我看能不能直接应用上。craftsman.dzy@gmail.com,非常感谢您

**Comment by blankqwq** [comment]
您好，仓库文件的OC就是EFI里的OC，因为我是双系统所以没有上传完整的EFI(省略了EFI下BOOT文件夹)

**Comment by flydzy** [comment]
好的，谢谢您
